// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Contacts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"pt-5\"><div class=\"container py-5\"><h2>Contact Us</h2><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates culpa, autem temporibus est delectus maiores adipisci tempore incidunt! Ad distinctio ea eligendi autem nesciunt vero eum quasi quas, placeat amet. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere saepe doloribus aut vel perspiciatis debitis sequi nulla? Eum, voluptatem perferendis. Nemo, aperiam officia illum quasi esse accusantium tempore rem nam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio dolore quo, eaque recusandae laboriosam veniam accusamus minus iste obcaecati magnam unde! Reiciendis facere earum ipsam voluptatum numquam vel unde sunt!</p></div><div class=\"container pb-5\"><img class=\"img-fluid img-thumbnail d-block w-100\" src=\"/static/images/tray.png\" alt=\"tray with coffee\"></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
