// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Contacts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"about py-8xl\" x-data=\"{ shown: false }\" x-intersect=\"shown = true\"><div class=\"container\" x-cloak x-show=\"shown\" x-transition.opacity.duration.2000ms><img class=\"img-fluid mb-xl\" src=\"/static/images/contacts.jpg\" alt=\"woman in living room\"><h2 class=\"capitalize mb-xs\">contact us</h2><p class=\"mb-lg\">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Obcaecati eum, sit quis id reiciendis omnis voluptatem pariatur et? Autem ducimus possimus iusto exercitationem perferendis, fugiat illum laborum minus consequuntur officia.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quae perferendis inventore in id culpa consequuntur quia, qui vero ipsam non quod accusantium, corrupti pariatur at blanditiis iste minus et sit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos repudiandae, sequi ullam quia exercitationem modi fugit repellat eos quo, saepe doloremque ad. Non pariatur perferendis aperiam. Perferendis rerum hic explicabo.</p><a href=\"/availability\" class=\"btn btn-full py-xs px-lg\"><p class=\"capitalize\">check rooms</p></a></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
