// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func GeneralsQuarters() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"pt-5\"><div class=\"container py-5\"><img class=\"img-fluid img-thumbnail mb-5\" src=\"/static/images/generals-quarters.png\" alt=\"generals quarters\"><h2>General's Quarters</h2><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet iste numquam, molestias explicabo repellendus cum quasi dolores modi mollitia delectus, possimus, eos ratione vero nisi minima ipsum similique. Animi, perspiciatis?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iusto facere, nesciunt voluptatum eaque debitis non perferendis pariatur, cupiditate commodi mollitia saepe tenetur voluptates totam natus voluptate quod libero, illo doloribus.</p><a href=\"/search-availability\" class=\"btn btn-primary\">Check Availability</a></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func MajorsSuite() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<section class=\"pt-5\"><div class=\"container py-5\"><img class=\"img-fluid img-thumbnail mb-5\" src=\"/static/images/majors-suite.png\" alt=\"majors suite\"><h2>Major's Suite</h2><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet iste numquam, molestias explicabo repellendus cum quasi dolores modi mollitia delectus, possimus, eos ratione vero nisi minima ipsum similique. Animi, perspiciatis?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iusto facere, nesciunt voluptatum eaque debitis non perferendis pariatur, cupiditate commodi mollitia saepe tenetur voluptates totam natus voluptate quod libero, illo doloribus.</p><a href=\"/search-availability\" class=\"btn btn-primary\">Check Availability</a></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
