// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Reservation struct {
	ID        int64
	FirstName string
	LastName  string
	Email     string
	Phone     string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	RoomID    int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Restriction struct {
	ID              int64
	RestrictionName string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Room struct {
	ID        int64
	RoomName  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RoomRestriction struct {
	ID            int64
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	RoomID        int64
	ReservationID int64
	RestrictionID int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID          int64
	FirstName   string
	LastName    string
	Email       string
	Password    string
	AccessLevel int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
