// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
  first_name,last_name,email,phone,start_date,end_date,room_id
) VALUES (
  $1,$2,$3,$4,$5,$6,$7
)
RETURNING id, first_name, last_name, email, phone, start_date, end_date, room_id, created_at, updated_at
`

type CreateReservationParams struct {
	FirstName string
	LastName  string
	Email     string
	Phone     string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	RoomID    int64
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.StartDate,
		arg.EndDate,
		arg.RoomID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.StartDate,
		&i.EndDate,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
