// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restrictions.sql

package db

import (
	"context"
)

const createRestriction = `-- name: CreateRestriction :one
INSERT INTO restrictions (
  restriction_name
) VALUES (
  $1
)
RETURNING id, restriction_name, created_at, updated_at
`

func (q *Queries) CreateRestriction(ctx context.Context, restrictionName string) (Restriction, error) {
	row := q.db.QueryRow(ctx, createRestriction, restrictionName)
	var i Restriction
	err := row.Scan(
		&i.ID,
		&i.RestrictionName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
