// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
  room_name
) VALUES (
  $1
)
RETURNING id, room_name, created_at, updated_at
`

func (q *Queries) CreateRoom(ctx context.Context, roomName string) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, roomName)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
