// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_restrictions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoomRestriction = `-- name: CreateRoomRestriction :one
INSERT INTO room_restrictions (
  start_date,end_date,room_id,reservation_id, restriction_id 
) VALUES (
  $1,$2,$3,$4,$5
)
RETURNING id, start_date, end_date, room_id, reservation_id, restriction_id, created_at, updated_at
`

type CreateRoomRestrictionParams struct {
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	RoomID        int64
	ReservationID int64
	RestrictionID int64
}

func (q *Queries) CreateRoomRestriction(ctx context.Context, arg CreateRoomRestrictionParams) (RoomRestriction, error) {
	row := q.db.QueryRow(ctx, createRoomRestriction,
		arg.StartDate,
		arg.EndDate,
		arg.RoomID,
		arg.ReservationID,
		arg.RestrictionID,
	)
	var i RoomRestriction
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.RoomID,
		&i.ReservationID,
		&i.RestrictionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
